dumpstate: remove -std=gnu99
-std=gnu99 no longer has effect now that dumpstate is C++.

The flag also break build if target platform is configured to default
gcc compiler since gcc throws warning for having -std=gnu99 when compiling
C++ and we have -Werror for the module.

Reproduce:
mm LOCAL_CLANG=false
...
error: command line option '-std=gnu99' is valid for C/ObjC but not for C++ [-Werror]

Change-Id: If1c272868ec4626873e7d91342b1fea51a15c52e